from django.urls import path, reverse_lazy
from . import views

app_name='workspaces'
urlpatterns = [
    path('', views.WorkspaceListView.as_view(), name='all'),
    path('workspace/<int:pk>/delete',
        views.WorkspaceDeleteView.as_view(success_url=reverse_lazy('workspaces:all')), name='workspace_delete'),
    path('workspace/<int:pk>/leave',
        views.WorkspaceLeaveView.as_view(success_url=reverse_lazy('workspaces:all')), name='workspace_leave'),
    path('workspace/<int:pk>/update',
        views.WorkspaceUpdateView.as_view(success_url=reverse_lazy('workspaces:all')), name='workspace_update'),
    path('workspace/<int:pk>/sharelink/<str:addr>',
        views.WorkspaceShareView.as_view(), name='workspace_share'),
    path('workspace/<int:pk>',
        views.ChannelListView.as_view(), name='channel_all'),
    path('channel/<int:pk>/delete',
        views.ChannelDeleteView.as_view(success_url=reverse_lazy('workspaces')), name='channel_delete'),
    path('channel/<int:pk>/leave',
        views.ChannelLeaveView.as_view(), name='channel_leave'),
    path('channel/<int:pk>/join',
        views.ChannelJoinView.as_view(), name='channel_join'),
    path('channel/<int:pk>/update',
        views.ChannelUpdateView.as_view(), name='channel_update'),
    path('workspace/<int:pk1>/user/<int:pk2>',
        views.UserChatView.as_view(), name='workspace_user'),
    path('workspace/<int:pk1>/user/<int:pk2>/update',
        views.UserUpdateView.as_view(), name='user_update'),
    path('user/<int:pk>',
        views.UserMessageCreateView.as_view(), name='user_message'),
    path('user/<int:pk>/message',
        views.UserMessages.as_view(), name='user_message_get'),
    path('usermsg/<int:pk>/delete',
        views.UserMessageDeleteView.as_view(), name='user_message_delete'),
]