# Generated by Django 2.2.5 on 2019-11-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20191121_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='updated_at',
        ),
    ]
