# Generated by Django 2.2.5 on 2019-11-24 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0003_auto_20191121_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(related_name='auth_users_of_channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
