# Generated by Django 2.2.5 on 2019-11-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_auto_20191126_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='sharelink',
            field=models.CharField(default='5TYbH5FU8PFkVn', max_length=20),
        ),
    ]
