# Generated by Django 2.2.5 on 2019-11-28 03:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0008_auto_20191127_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='sharelink',
        ),
        migrations.CreateModel(
            name='Sharelink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2019, 12, 28, 3, 2, 26, 465377))),
                ('addr', models.CharField(default='w4DbVzng8BHLLf', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Workspace')),
            ],
        ),
    ]
