# Generated by Django 2.2.5 on 2019-11-28 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_auto_20191128_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='addr',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 3, 54, 38, 788859)),
        ),
        migrations.AlterUniqueTogether(
            name='sharelink',
            unique_together={('workspace', 'addr')},
        ),
    ]
