# Generated by Django 2.2.5 on 2019-12-04 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0010_auto_20191128_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='seen',
            field=models.ManyToManyField(default=[models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)], related_name='users_seened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 19, 45, 25, 237082)),
        ),
    ]
