# Generated by Django 2.2.5 on 2019-12-04 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_auto_20191204_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='dmsgunseen',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='unseen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 20, 24, 6, 345320)),
        ),
    ]
